name: EnchantPro
version: 1.0
description: Custom enchantments plugin.
api-version: 1.16
main: DevJam.EnchantPro
depend: [WorldGuard]
commands:
  test:
    description: Temporary, should not be in the final version.
    usage: /<command>
    permission: enchantpro.test
  ep:
    description: EnchantPro command.
    usage: /ep <command>
  enchantpro:
    description: EnchantPro command.
    usage: /enchantpro <command>