name: EnchantPro
version: 1.0
main: DevJam.EnchantPro
commands:
  versioninfo:
    description: Gives the version information for the EnchantPro plugin.
    usage: /<command>
    permission: enchantpro.versioninfo