name: EnchantPro
version: 1.0
api-version: 1.16
main: DevJam.EnchantPro
commands:
  test:
    description: Temporary, should not be in the final version.
    usage: /<command>
    permission: enchantpro.test
  ep:
    description: EnchantPro command.
    usage: /ep <command>